project_id = "egrljooargciueeppecq"

[functions.ai-chat]
verify_jwt = true

[functions.ai-financial-advisor]
verify_jwt = true

[functions.send-budget-alerts]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.process-recurring-transactions]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true